services:
  db:
    volumes:
        - ./sql-scripts:/docker-entrypoint-initdb.d
    container_name: powerfitness_database
    image: mysql
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_USER=user
        - MYSQL_PASSWORD=password
        - MYSQL_DATABASE=powerfitness